spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatisplus_db?serverTimezone=UTC
    username: root
    password: wangfei.*0928
  main:
    banner-mode: off

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    #????????
    db-config:
      table-prefix: tb_
      #????id
      id-type: assign_id
      # ????????
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

